apiVersion: v1
kind: Service
metadata:
  name: nodejs-contacts-backend
  labels:
    app: nodejs-contacts
    tier: backend
spec:
  type: NodePort
  selector:
    app: nodejs-contacts
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
    nodePort: 30456