apiVersion: v1
kind: Service
metadata:
  name: nodejs-contacts-frontend
  labels:
    app: nodejs-contacts
    tier: frontend
spec:
  type: NodePort
  selector:
    app: nodejs-contacts
    tier: frontend
  ports:
  - port: 80
    targetPort: http-server
    nodePort: 30455