apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-contacts-frontend
  labels:
    app: nodejs-contacts
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-contacts
      tier: frontend
  template:
    metadata:
      labels:
        app: nodejs-contacts
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: nodejs-contacts-frontend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: REACT_APP_SERVER_URL
          value: nodejs-contacts-backend:8080/contacts